/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.ark.*;

public class App {
    public String newAddressFromPassphrase(String passphrase) {
        return Crypto.getAddress(Crypto.getKeys(passphrase));
    }

    public Transaction createDummyTransaction(String passphrase) {
        return Transaction.createTransaction("AN7BURQn5oqBRBADeWhmmUMJGQTy5Seey3", 100000000000l, "vendorField", passphrase);
    }

    public static void main(String[] args) {
        App app = new App();
        System.out.println(app.newAddressFromPassphrase("this is a top secret passphrase"));
        System.out.println(app.createDummyTransaction("this is a top secret passphrase"));
    }
}
